### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Yukaii** [Yukaii/ics-scheduler#6]
### Online checklist
- Contribution Guide
  - [x] Crawler specification
  - [ ] ~~PR template~~
  - [x] LICENSE
- Architecture Guide
  - [x] About Travis CI deployment
  - [x] Data Struture
- Multi Platform Guide #9 
  - [x] iOS Guide
  - [x] Google Calendar Guide
  - [x] macOS Calendar App Guide

**Comment by Yukaii** [comment]
先關惹，改用 GitHub Projects 管版試試 😆
